name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  ROOT_VERSION: 6-22-00

jobs:
  job:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Build
        run: cmake --build build
      - name: Install
        run: cmake --install .

